# Generated by Django 4.2.4 on 2023-12-27 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NivelCarreira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('bandafuncional', models.ImageField(upload_to='')),
                ('salario', models.DecimalField(decimal_places=3, max_digits=5)),
                ('carreira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.carreira')),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.departamento')),
                ('nivelCarreira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.nivelcarreira')),
            ],
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('bi', models.CharField(max_length=13)),
                ('data_nascimento', models.DateField()),
                ('naturalidade', models.CharField(max_length=255)),
                ('nacionalidade', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=1)),
                ('morada', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.funcao')),
            ],
        ),
    ]
