# Generated by Django 4.2.4 on 2023-12-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelcarreira',
            name='bandafuncional',
            field=models.IntegerField(),
        ),
    ]
