# Generated by Django 4.2.4 on 2023-12-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_progresso_carreira_carreira_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelcarreira',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
