# Generated by Django 4.2.4 on 2023-12-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_alter_nivelcarreira_salario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcao',
            name='nivelCarreira',
        ),
        migrations.AddField(
            model_name='funcao',
            name='nivelCarreira',
            field=models.ManyToManyField(to='gestao.nivelcarreira'),
        ),
    ]
