# Generated by Django 4.2.4 on 2023-12-27 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_remove_funcao_nivelcarreira_funcao_nivelcarreira'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='nivel_carreira_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.nivelcarreira'),
        ),
    ]
