# Generated by Django 4.2.4 on 2023-12-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_colaboradores_nivel_carreira_atual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradores',
            old_name='nome',
            new_name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='colaboradores',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='colaboradores',
            name='sobrenome',
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='bi',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
