# Generated by Django 4.2.4 on 2024-01-06 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_rename_nome_colaboradores_nome_completo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Motivo', models.CharField(choices=[('acidente_de_trabalho', 'Acidente de trabalho'), ('doença', 'Doença'), ('ausencia_por_funeral', 'Ausência por funeral'), ('doacao_de_sangue', 'Doação de sangue'), ('ausencia_em_servico', 'Ausência em serviço'), ('falecimento_de_familiar_do_1_grau', 'Falecimento de familiar do 1º grau'), ('casamento', 'Casamento'), ('falecimento_de_familiar_do_2_grau', 'Falecimento de familiar do 2º grau'), ('convocacao_oficial', 'Convocação oficial'), ('maternidade/paternidade', 'Maternidade/Paternidade'), ('dispensa_mensal_de_servico', 'Dispensação mensal de serviço'), ('tratamento_de_assuntos_pessoais', 'Tratamento de assuntos pessoais')], max_length=100)),
                ('inicio_falta', models.DateField()),
                ('inicio_Fim', models.DateField()),
                ('Aprovado', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=100)),
                ('Colaboradores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.colaboradores')),
            ],
        ),
    ]
