# Generated by Django 4.2.4 on 2024-01-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_justificativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='data_nascimento',
            field=models.DateField(default='11-11-200'),
        ),
    ]
