# Generated by Django 4.2.4 on 2024-01-07 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_alter_colaboradores_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='data_nascimento',
            field=models.DateField(default='2000-11-11'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='funcao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestao.funcao'),
        ),
    ]
