# Generated by Django 4.2.4 on 2024-01-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_alter_colaboradores_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativo',
            name='ficheiro',
            field=models.FileField(default=1, upload_to='media/justificativo'),
            preserve_default=False,
        ),
    ]
