# Generated by Django 4.2.4 on 2024-01-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_justificativo_ficheiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justificativo',
            name='Aprovado',
        ),
        migrations.AddField(
            model_name='justificativo',
            name='Justificado',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=100),
        ),
        migrations.AlterField(
            model_name='justificativo',
            name='ficheiro',
            field=models.FileField(blank=True, null=True, upload_to='media/justificativo'),
        ),
        migrations.AlterField(
            model_name='justificativo',
            name='inicio_Fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
