# Generated by Django 4.2.4 on 2024-01-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0012_remove_justificativo_aprovado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='AtestadoMedico',
            field=models.FileField(blank=True, null=True, upload_to='media/Funcionario', verbose_name='Atestado Médico'),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='Certificado',
            field=models.FileField(blank=True, null=True, upload_to='media/Funcionario', verbose_name='Certificado'),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='Curriculo',
            field=models.FileField(blank=True, null=True, upload_to='media/Funcionario', verbose_name='Curriculo'),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='ExtratoBancario',
            field=models.FileField(blank=True, null=True, upload_to='media/Funcionario', verbose_name='Extrato Bancario'),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='FBI',
            field=models.FileField(blank=True, null=True, upload_to='media/Funcionario', verbose_name='Copia do BI'),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='NFI',
            field=models.FileField(blank=True, null=True, upload_to='media/Funcionario', verbose_name='Número de Contribuinte'),
        ),
    ]
