# Generated by Django 4.2.4 on 2024-01-30 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0013_colaboradores_atestadomedico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='DataFim',
            field=models.DateField(blank=True, default='2018-11-11', null=True, verbose_name='Fim do Contrato'),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='DataIncio',
            field=models.DateField(default='2018-11-11', verbose_name='Iniciona de Contrato'),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='TipodeContrato',
            field=models.CharField(choices=[('Tempo Determinado', 'Tempo Determinado'), ('Indeterminado', 'Indeterminado')], default=1, max_length=200, verbose_name='Tipo de Contrato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='Curriculo',
            field=models.FileField(blank=True, null=True, upload_to='media/Funcionario', verbose_name='Currículo'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='ExtratoBancario',
            field=models.FileField(blank=True, null=True, upload_to='media/Funcionario', verbose_name='Extrato Bancário'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='funcao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestao.funcao', verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='nome_completo',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.CreateModel(
            name='CursosPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=255)),
                ('instituicao', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=255)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Concluído', 'Concluído'), ('Em andamento', 'Em andamento'), ('Não concluído', 'Não concluído')], max_length=20)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.colaboradores')),
            ],
        ),
    ]
