# Generated by Django 4.2.4 on 2024-02-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0014_colaboradores_datafim_colaboradores_dataincio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='DataIncio',
            field=models.DateField(default='2018-11-11', verbose_name='Inicio de Contrato'),
        ),
        migrations.AlterField(
            model_name='cursospagos',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Fim do Curso'),
        ),
        migrations.AlterField(
            model_name='cursospagos',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Início do Curso'),
        ),
        migrations.AlterField(
            model_name='cursospagos',
            name='instituicao',
            field=models.CharField(max_length=255, verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='cursospagos',
            name='status',
            field=models.CharField(choices=[('Concluído', 'Concluído'), ('Em andamento', 'Em andamento'), ('Não concluído', 'Não concluído')], max_length=20, verbose_name='Estado do Curso'),
        ),
        migrations.AlterField(
            model_name='cursospagos',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo'),
        ),
    ]
