# Generated by Django 4.2.4 on 2024-01-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desempenho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_estado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
