# Generated by Django 4.2.4 on 2024-01-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desempenho', '0002_alter_tarefa_data_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='Aprovado',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=100),
        ),
    ]
