# Generated by Django 4.2.4 on 2024-02-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Desempenho', '0003_alter_tarefa_aprovado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_meta', models.CharField(max_length=255)),
                ('formula_meta', models.CharField(max_length=255)),
                ('Baseline', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_meta', models.CharField(choices=[('hr', 'hr'), ('%', '%')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Perfomacemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hoshine', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Plan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_indicador', models.CharField(choices=[('verde', 'Verde'), ('amarelo', 'Amarelo'), ('vermelho', 'Vermelho')], max_length=10)),
                ('Mes', models.CharField(choices=[('janeiro', 'Janeiro'), ('fevereiro', 'Fevereiro'), ('marco', 'Março'), ('abril', 'Abril'), ('maio', 'Maio'), ('junho', 'Junho'), ('julho', 'Julho'), ('agosto', 'Agosto'), ('setembro', 'Setembro'), ('outubro', 'Outubro'), ('novembro', 'Novembro'), ('dezembro', 'Dezembro')], max_length=10)),
                ('data_medicao', models.DateField(auto_now=True)),
                ('Metas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Desempenho.performancemodel')),
            ],
        ),
    ]
