# Generated by Django 4.2.4 on 2024-02-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desempenho', '0004_performancemodel_perfomacemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemodel',
            name='Hoshin',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
