# Generated by Django 4.2.4 on 2024-02-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Desempenho', '0005_performancemodel_hoshin'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelPerforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('Descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='performancemodel',
            name='NivePr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Desempenho.nivelperforme'),
            preserve_default=False,
        ),
    ]
