# Generated by Django 4.2.4 on 2024-02-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desempenho', '0006_nivelperforme_performancemodel_nivepr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfomacemes',
            name='Hoshine',
        ),
        migrations.AlterField(
            model_name='perfomacemes',
            name='status_indicador',
            field=models.CharField(blank=True, choices=[('verde', 'Verde'), ('amarelo', 'Amarelo'), ('vermelho', 'Vermelho')], max_length=10, null=True),
        ),
    ]
