# Generated by Django 4.2.4 on 2024-02-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desempenho', '0007_remove_perfomacemes_hoshine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfomacemes',
            name='Mes',
        ),
        migrations.RemoveField(
            model_name='performancemodel',
            name='Baseline',
        ),
        migrations.RemoveField(
            model_name='performancemodel',
            name='Hoshin',
        ),
        migrations.AddField(
            model_name='perfomacemes',
            name='Baseline',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfomacemes',
            name='Data',
            field=models.DateField(default=1, verbose_name='Mês'),
            preserve_default=False,
        ),
    ]
