# Generated by Django 4.2.4 on 2024-02-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desempenho', '0008_remove_perfomacemes_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfomacemes',
            name='Data',
            field=models.DateField(),
        ),
    ]
