# Generated by Django 4.2.4 on 2024-02-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Desempenho', '0009_alter_perfomacemes_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfomacemes',
            name='Data',
        ),
    ]
