# Generated by Django 4.2.4 on 2024-02-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desempenho', '0011_perfomacemes_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfomacemes',
            name='Mes',
            field=models.DateField(auto_now_add=True),
        ),
    ]
