# Generated by Django 4.2.4 on 2024-02-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Desempenho', '0012_alter_perfomacemes_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfomacemes',
            name='Mes',
        ),
    ]
