# Generated by Django 4.2.4 on 2024-02-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desempenho', '0013_remove_perfomacemes_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfomacemes',
            name='Baseline2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
