# Generated by Django 4.2.4 on 2024-02-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desempenho', '0014_perfomacemes_baseline2'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfomacemes',
            name='data_mes',
            field=models.DateField(auto_now=True),
        ),
    ]
