# Generated by Django 4.2.4 on 2024-02-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desempenho', '0015_perfomacemes_data_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfomacemes',
            name='Baseline2',
        ),
        migrations.AlterField(
            model_name='perfomacemes',
            name='data_mes',
            field=models.DateField(),
        ),
    ]
