# Generated by Django 4.2.4 on 2024-02-18 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Desempenho', '0016_remove_perfomacemes_baseline2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados_das_Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Baseline', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_indicador', models.CharField(blank=True, choices=[('verde', 'Verde'), ('amarelo', 'Amarelo'), ('vermelho', 'Vermelho')], max_length=10, null=True)),
                ('data_medicao', models.DateField(auto_now=True)),
                ('data_mes', models.DateField()),
                ('Metas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Desempenho.performancemodel')),
            ],
        ),
    ]
