# Generated by Django 4.2.4 on 2024-02-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desempenho', '0017_resultados_das_metas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultados_das_metas',
            name='Plan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Perfomacemes',
        ),
    ]
