# Generated by Django 4.2.4 on 2024-02-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desempenho', '0019_alter_resultados_das_metas_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancemodel',
            name='NivePr',
        ),
        migrations.AddField(
            model_name='performancemodel',
            name='NivePr',
            field=models.ManyToManyField(to='Desempenho.nivelperforme'),
        ),
    ]
